### ISSUE TITLE
Editar el archivo Presentacion

### ISSUE THREAD

**Issue by Coder-Maverick** [Coder-Maverick/Trabajo-Grupal-ISPC#3]
Esta tarea es solo para ir practicando editar archivos, agregar commit, etc.

**Comment by ahroncich7** [comment]
Se propone como actividad, crear un archivo.md para que todos vayamos cargando nuestro nombre y breve descripción de nuestra experiencia en el mundo IT (Super breve, algo como "Actualmente trabajo en diseño web" o "una vez reinicié una laptop").
Supongo que habría que abrir un branch, editar el archivo con nuestra info y commitearlo. Si alguien la tiene mas clara y no es así, que aporte.

**Comment by ahroncich7** [comment]
Corrijo, el archivo ya existe. Entonces vayamos editándolo para poner en práctica el tema de los branch. Insisto con eso a pesar de que aún no lo vimos (al menos en los encuentros), porque en la última clase en vivo el profe Mateo dijo que los cambios debían ser hechos localmente, comiteados y luego hacer el push al repo remoto, el que está acá el Github.

**Comment by dunca2022** [comment]
[Uploading CV ISPC.pdf…]()

**Comment by dunca2022** [comment]
ahi esta mi CV
